import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dkoch
 */
public class JFrame_Task_1 extends javax.swing.JFrame {
    ArrayList<Room> roomList;    
    private int currentInd;

    /**
     * Creates new form JFrame_Task_1
     */
    public JFrame_Task_1() {
        initComponents();
        roomList  = new ArrayList <>();     
        currentInd = roomList.size()-1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textLengthRoom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textWidthRoom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textHeightRoom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerCrn = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCount = new javax.swing.JTextField();
        jButtonNewRoom = new javax.swing.JButton();
        jButtonDelRoom = new javax.swing.JButton();
        jButtonCalcSquare = new javax.swing.JButton();
        jTextFieldCalcSquareWithout = new javax.swing.JTextField();
        jButtonSquareRoomWithout = new javax.swing.JButton();
        jTextFieldSquareRoom = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRooms = new javax.swing.JTable();
        jButtonInsertData = new javax.swing.JButton();
        jButtonDelData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Вычисление площади стен комнаты");

        jLabel2.setText("Длина комнаты, м.");

        jLabel3.setText("Ширина комнаты, м.");

        jLabel4.setText("Высота до потолка, м.");

        jLabel5.setText("Выбор элемента:");

        jSpinnerCrn.addChangeListener(this::jSpinnerCrnStateChanged);

        jLabel6.setText("Кол-во элементов:");

        jButtonNewRoom.setText("Новый");
        jButtonNewRoom.addActionListener(this::jButtonNewRoomActionPerformed);

        jButtonDelRoom.setText("Удалить");
        jButtonDelRoom.addActionListener(this::jButtonDelRoomActionPerformed);

        jButtonCalcSquare.setText("Площадь стен, м2");
        jButtonCalcSquare.addActionListener(this::jButtonCalcSquareActionPerformed);

        jButtonSquareRoomWithout.setText("Площадь стен без окна и двери, м2");
        jButtonSquareRoomWithout.addActionListener(this::jButtonSquareRoomWithoutActionPerformed);

        jTextFieldSquareRoom.setActionCommand("<Not Set>");

        jTableRooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Длина", "Ширина", "Высота", "S1", "S2"
            }
        ) {
            final boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRooms.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableRooms);
        if (jTableRooms.getColumnModel().getColumnCount() > 0) {
            jTableRooms.getColumnModel().getColumn(0).setResizable(false);
            jTableRooms.getColumnModel().getColumn(1).setResizable(false);
            jTableRooms.getColumnModel().getColumn(2).setResizable(false);
            jTableRooms.getColumnModel().getColumn(3).setResizable(false);
            jTableRooms.getColumnModel().getColumn(4).setResizable(false);
        }

        jButtonInsertData.setText("Внести данные в таблицу");
        jButtonInsertData.addActionListener(this::jButtonInsertDataActionPerformed);

        jButtonDelData.setText("Удалить данные из таблицы");
        jButtonDelData.addActionListener(this::jButtonDelDataActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(textWidthRoom)
                                            .addComponent(textLengthRoom)
                                            .addComponent(textHeightRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jSpinnerCrn, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jButtonNewRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(92, 92, 92)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldCount)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonDelRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButtonCalcSquare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSquareRoomWithout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonInsertData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldCalcSquareWithout)
                                    .addComponent(jTextFieldSquareRoom)
                                    .addComponent(jButtonDelData, javax.swing.GroupLayout.PREFERRED_SIZE, 180, Short.MAX_VALUE))
                                .addGap(28, 28, 28))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textLengthRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textWidthRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textHeightRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinnerCrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNewRoom)
                    .addComponent(jButtonDelRoom))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSquareRoom)
                    .addComponent(jButtonCalcSquare))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCalcSquareWithout)
                    .addComponent(jButtonSquareRoomWithout))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertData)
                    .addComponent(jButtonDelData))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewRoomActionPerformed
        setRoom();
        roomList.add(new Room());
        currentInd = roomList.size()-1;
        getRoom();
        jTextFieldCount.setText(""+(currentInd+1));
        jSpinnerCrn.setValue(currentInd);
    }//GEN-LAST:event_jButtonNewRoomActionPerformed

    private void jButtonDelRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelRoomActionPerformed
        roomList.remove(currentInd);
        currentInd = roomList.size()-1;
        if (currentInd == roomList.size()) {
            currentInd--;
            jSpinnerCrn.setValue(currentInd);
        } else {
            getRoom();
        }
        jTextFieldCount.setText("" + roomList.size());
    }//GEN-LAST:event_jButtonDelRoomActionPerformed

    private void jSpinnerCrnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerCrnStateChanged
        setRoom();
        currentInd = (int) jSpinnerCrn.getValue();
        jTextFieldSquareRoom.setText(null);
        jTextFieldCalcSquareWithout.setText(null);
        if (currentInd >= roomList.size()) {
            currentInd = roomList.size()-1;
            jSpinnerCrn.setValue(currentInd);
        } else if (currentInd < 0) {
            currentInd = 0;
            jSpinnerCrn.setValue(currentInd);
        }
        getRoom();
    }//GEN-LAST:event_jSpinnerCrnStateChanged

    private void jButtonCalcSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcSquareActionPerformed
        setRoom();
        for (Room room : roomList) {
            room.calcSquareWalls();
            DecimalFormat dF = new DecimalFormat("0.###");
            String value = dF.format(room.square);
            jTextFieldSquareRoom.setText(value);
        }
        getRoom();
    }//GEN-LAST:event_jButtonCalcSquareActionPerformed

    private void jButtonSquareRoomWithoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSquareRoomWithoutActionPerformed
        setRoom();
        for (Room room : roomList) {
            room.calcSquareWallsWithoutDoorAndWindow();
            DecimalFormat dF = new DecimalFormat("0.###");
            String value = dF.format(room.squareWithout);
            jTextFieldCalcSquareWithout.setText(value);
        }
        getRoom();
    }//GEN-LAST:event_jButtonSquareRoomWithoutActionPerformed

    private void jButtonInsertDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertDataActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableRooms.getModel(); // привязка модели к таблице
        model.addRow(new Object[]{textLengthRoom.getText(), textWidthRoom.getText(), textHeightRoom.getText(),
        jTextFieldSquareRoom.getText(), jTextFieldCalcSquareWithout.getText()}); // заполнение данных в таблицк
    }//GEN-LAST:event_jButtonInsertDataActionPerformed

    private void jButtonDelDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelDataActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableRooms.getModel(); // привязка модели к таблице
        model.removeRow(jTableRooms.getSelectedRow());
    }//GEN-LAST:event_jButtonDelDataActionPerformed
    
    protected void getRoom(){
        if (currentInd >= 0) {
            textLengthRoom.setText(String.valueOf(roomList.get(currentInd).length));
            textWidthRoom.setText(String.valueOf(roomList.get(currentInd).width));
            textHeightRoom.setText(String.valueOf(roomList.get(currentInd).height));
        }
    }
    
    protected void setRoom(){
        if ((currentInd >= 0) && (textLengthRoom.getText() != null)) {
            roomList.get(currentInd).length = Double.parseDouble(textLengthRoom.getText());
            roomList.get(currentInd).width = Double.parseDouble(textWidthRoom.getText());

            try {
                roomList.get(currentInd).width = new Double (textWidthRoom.getText());
            } catch (NumberFormatException e) {
                roomList.get(currentInd).width = 0;
                textWidthRoom.setText(null);
            }

            try {
                roomList.get(currentInd).height = new Double(textHeightRoom.getText());
            } catch (NumberFormatException e) {
                roomList.get(currentInd).height = 0;
                textHeightRoom.setText(null);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Task_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrame_Task_1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcSquare;
    private javax.swing.JButton jButtonDelData;
    private javax.swing.JButton jButtonDelRoom;
    private javax.swing.JButton jButtonInsertData;
    private javax.swing.JButton jButtonNewRoom;
    private javax.swing.JButton jButtonSquareRoomWithout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerCrn;
    private javax.swing.JTable jTableRooms;
    private javax.swing.JTextField jTextFieldCalcSquareWithout;
    private javax.swing.JTextField jTextFieldCount;
    private javax.swing.JTextField jTextFieldSquareRoom;
    private javax.swing.JTextField textHeightRoom;
    private javax.swing.JTextField textLengthRoom;
    private javax.swing.JTextField textWidthRoom;
    // End of variables declaration//GEN-END:variables
    }
