import javax.swing.*;
import java.text.DecimalFormat;
import java.util.ArrayList;

/**
 *
 * @author dkoch
 */
public class JFrame extends javax.swing.JFrame {
    ArrayList<Office> officeList;    
    private int currentInd;
       
    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        officeList  = new ArrayList<>();
        currentInd = officeList.size()-1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLengthOfficeHall = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldWidthOfficeHall = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldHeightOfficeHall = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldLengthOfficeRoom = new javax.swing.JTextField();
        jTextFieldWidthOfficeRoom = new javax.swing.JTextField();
        jTextFieldHeightOfficeRoom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSpinnerCrn = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCount = new javax.swing.JTextField();
        jButtonNewOffice = new javax.swing.JButton();
        jButtonDelOffice = new javax.swing.JButton();
        jButtonCalcPaintCons = new javax.swing.JButton();
        jTextFieldPaintCons = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Приложение для расчета расхода краски");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setText("Длина коридора, м.");

        jLabel3.setText("Ширина коридора, м.");

        jLabel4.setText("Высота коридора, м.");

        jLabel5.setText("Длина комнаты, м.");

        jLabel6.setText("Ширина комнаты, м.");

        jLabel7.setText("Высота комнаты, м.");

        jLabel8.setText("Выбор элемента");

        jSpinnerCrn.addChangeListener(this::jSpinnerCrnStateChanged);

        jLabel9.setText("Кол-во элементов");

        jButtonNewOffice.setText("Новый");
        jButtonNewOffice.addActionListener(this::jButtonNewOfficeActionPerformed);

        jButtonDelOffice.setText("Удалить");
        jButtonDelOffice.addActionListener(this::jButtonDelOfficeActionPerformed);

        jButtonCalcPaintCons.setText("Расчитать расход краски, л.");
        jButtonCalcPaintCons.addActionListener(this::jButtonCalcPaintConsActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(134, 134, 134))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldLengthOfficeHall, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldWidthOfficeHall, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldHeightOfficeHall, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldHeightOfficeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldLengthOfficeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldWidthOfficeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldCount, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonNewOffice)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonDelOffice)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSpinnerCrn, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCalcPaintCons)
                                .addGap(28, 28, 28)
                                .addComponent(jTextFieldPaintCons, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldLengthOfficeHall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldLengthOfficeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldWidthOfficeHall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldWidthOfficeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldHeightOfficeHall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldHeightOfficeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerCrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewOffice)
                    .addComponent(jButtonDelOffice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCalcPaintCons)
                    .addComponent(jTextFieldPaintCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewOfficeActionPerformed
        setOffice();
        officeList.add(new Office());
        currentInd = officeList.size()-1;
        getOffice();
        jTextFieldCount.setText(""+(currentInd+1));
        jSpinnerCrn.setValue(currentInd);
    }//GEN-LAST:event_jButtonNewOfficeActionPerformed

    private void jButtonDelOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelOfficeActionPerformed
        officeList.remove(currentInd);
        currentInd = officeList.size()-1;
        if (currentInd == officeList.size()) {
            currentInd--;
            jSpinnerCrn.setValue(currentInd);
        } else {
            getOffice();
        }
        jTextFieldCount.setText("" + officeList.size());
    }//GEN-LAST:event_jButtonDelOfficeActionPerformed

    private void jSpinnerCrnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerCrnStateChanged
        setOffice();
        currentInd = (int) jSpinnerCrn.getValue();
        jTextFieldPaintCons.setText(null);
        if (currentInd >= officeList.size()) {
            currentInd = officeList.size()-1;
            jSpinnerCrn.setValue(currentInd);
        } else if (currentInd < 0) {
            currentInd = 0;
            jSpinnerCrn.setValue(currentInd);
        }
        getOffice();
    }//GEN-LAST:event_jSpinnerCrnStateChanged

    private void jButtonCalcPaintConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcPaintConsActionPerformed
        setOffice();
        for (Office office : officeList) {
            office.calcSquareWallsWithoutDoorAndWindow();
            office.calcSquareHallWallsWithoutDoorAndWindow();
            office.calcPaintConsOffice();
            DecimalFormat dF = new DecimalFormat("0.###");
            String value = dF.format(office.paintConsOffice);
            jTextFieldPaintCons.setText(value);
        }
        getOffice();
    }//GEN-LAST:event_jButtonCalcPaintConsActionPerformed

    protected void getOffice(){
        if (currentInd >= 0) {
            jTextFieldLengthOfficeHall.setText(String.valueOf(officeList.get(currentInd).lengthHall));
            jTextFieldWidthOfficeHall.setText(String.valueOf(officeList.get(currentInd).widthHall));
            jTextFieldHeightOfficeHall.setText(String.valueOf(officeList.get(currentInd).heightHall));
            jTextFieldLengthOfficeRoom.setText(String.valueOf(officeList.get(currentInd).length));
            jTextFieldWidthOfficeRoom.setText(String.valueOf(officeList.get(currentInd).width));
            jTextFieldHeightOfficeRoom.setText(String.valueOf(officeList.get(currentInd).height));
        }
    }
    
    protected void setOffice(){
        // заполнение полей коридора
        if ((currentInd >= 0) && (jTextFieldLengthOfficeHall.getText() != null)) {
            officeList.get(currentInd).lengthHall = Double.parseDouble(jTextFieldLengthOfficeHall.getText());
            officeList.get(currentInd).widthHall = Double.parseDouble(jTextFieldWidthOfficeHall.getText());

            try {
                officeList.get(currentInd).widthHall = new Double (jTextFieldWidthOfficeHall.getText());
            } catch (NumberFormatException e) {
                officeList.get(currentInd).widthHall = 0;
                jTextFieldWidthOfficeHall.setText(null);
            }

            try {
                officeList.get(currentInd).heightHall = new Double(jTextFieldHeightOfficeHall.getText());
            } catch (NumberFormatException e) {
                officeList.get(currentInd).heightHall = 0;
                jTextFieldHeightOfficeHall.setText(null);
            }
            // заполнение полей комнаты
            try {
                officeList.get(currentInd).length = new Double(jTextFieldLengthOfficeRoom.getText());
            } catch (NumberFormatException e) {
                officeList.get(currentInd).length = 0;
                jTextFieldLengthOfficeRoom.setText(null);
            }
            
            try {
                officeList.get(currentInd).width = new Double(jTextFieldWidthOfficeRoom.getText());
            } catch (NumberFormatException e) {
                officeList.get(currentInd).width = 0;
                jTextFieldWidthOfficeRoom.setText(null);
            }
            
            try {
                officeList.get(currentInd).height = new Double(jTextFieldHeightOfficeRoom.getText());
            } catch (NumberFormatException e) {
                officeList.get(currentInd).height = 0;
                jTextFieldHeightOfficeRoom.setText(null);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcPaintCons;
    private javax.swing.JButton jButtonDelOffice;
    private javax.swing.JButton jButtonNewOffice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinnerCrn;
    private javax.swing.JTextField jTextFieldCount;
    private javax.swing.JTextField jTextFieldHeightOfficeRoom;
    private javax.swing.JTextField jTextFieldHeightOfficeHall;
    private javax.swing.JTextField jTextFieldLengthOfficeHall;
    private javax.swing.JTextField jTextFieldLengthOfficeRoom;
    private javax.swing.JTextField jTextFieldPaintCons;
    private javax.swing.JTextField jTextFieldWidthOfficeHall;
    private javax.swing.JTextField jTextFieldWidthOfficeRoom;
    // End of variables declaration//GEN-END:variables
}
